# -*- coding: utf-8 -*-
"""Escape Character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cz3k6hmlqEv7rbVanY0vaofZIEsMr5rw
"""

print ('dia berkata : "pergilah"')

print ("aku menimpali:\"apakah kau ingin aku'angkat kaki'?!\"")

print("\\(^_^/)/(\\-_-/)")