# -*- coding: utf-8 -*-
"""manipulasi string 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cf7NT_F0Yi9emqfp6cc5pGEP0sGV-IN2
"""

template = "halo saya %s dari %s"
print(template %('radinka albasith','indonesia'))

template = 'halo saya{radinka} dari {tokyo}'
template_2 = 'halo saya makan {} dan minum {}'

print(template.format(radinka='radinka',tokyo='indonesia'))
print(template_2.format('bakso','es jeruk'))

nama = 'muhammad radinka'
asal = 'japan'

print(f'perkenalkan saya {nama} dari {asal}')

alamat = 'bandung, jawabarat, papua'

print(alamat.split())
print(alamat.split(','))
print(alamat.split(', '))

"""memecah string

"""

print('@'.join(['kamu','gak','suka']))

print('halo selamat pagi!'.upper())
print('halo selamat siang!'.upper())

print('halo selamat pagi!'.lower())
print('halo selamat siang!'.lower())

"""mengubah string menjadi title case"""

print('daun tidak pernah membenci angin'.title())
print('laskar pelangi'.title())

"""mengubah string menjadi revers case"""

print('indonesia adalah negara kepulauan'.swapcase())
print('Aku Cinta Negriku'.swapcase())

"""mencari kata pada string"""

angka = '12345'

print('index angka 3:',angka.find('3'))
print('index angka 45:',angka.find('45'))
print('index angka 35:',angka.find('35'))

ibu_kota = 'jakarta'

print(ibu_kota.replace('a','i'))
print(ibu_kota.replace('a',''))

paragraf = 'baru baru ini telah ditemukan sebuah meteor di suatu suangai'
x = paragraf.count('di')

print(f'kata""di"muncul sebanyak {x} kali')