# -*- coding: utf-8 -*-
"""manipulasi string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g1o86JJVyv8h9qAyIyfGix7BzKP7VCba

**String**
"""

nama = 'radinka albasith'
asal = "bandar lampung"

print(nama)

print(asal)

"""**manipulasi**"""

print(nama,asal)

print(nama+asal)

print("hallo,nama saya",nama)

print("hallo,nama saya",nama,"asal saya dari",asal)

data_lengkap = nama + asal

print(data_lengkap)

"""**string + no string**"""

asal_kota = "Bandar Lampung"
kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3

print(asal_kota_x3)