# -*- coding: utf-8 -*-
"""tipe data casting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IibM_bDjM9OtHcYUJ-A0WUwoK8rtSOeA
"""

nama = 'Radinka'
usia = 20
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

usia = input('Masukan usia anda')

print(type(usia))

panjang = int(input('Masukan panjang'))
lebar = int(input('Masukan lebar'))

print('luas=', panjang * lebar)

a = 10 / 2
print(type(a))

b = 1 / 2
print(type(b))

kata = 'jeruk' * 5

print(type(kata))
print(kata)

nama = 'radinka'
tahun_lahir = 2000

print(nama + 'lahir di tahun' + str(tahun_lahir))