# -*- coding: utf-8 -*-
"""Tugas 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S07DUdBU9vIRBwO2_gNahLC6w85R3uVc
"""

data_kotor = "   #001-wahyu aji-informatika-python,java,php-aktif   "

data_bersih = data_kotor.strip().replace('#', '')

list_data = data_bersih.split("-")

id_pendaftaran = list_data[0]
nama_lengkap = list_data[1].title()
program_studi = list_data[2].title()
skill_dikuasai = list_data[3]
status = list_data[4].upper()

list_skill = skill_dikuasai.split(",")
skill_join = " & ".join(list_skill)

panjang_id = len(id_pendaftaran)
jumlah_skill = len(list_skill)

print(f"ID Pendaftaran: {id_pendaftaran}")
print(f"Nama Lengkap: {nama_lengkap}")
print(f"Program Studi: {program_studi}")
print(f"Skill Dikuasai: {skill_join}")
print(f"Jumlah Skill: {jumlah_skill}")
print(f"Status: {status}")