# -*- coding: utf-8 -*-
"""UTS KEL 4 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJXpjFngVf_NIdoFY5vxaEAk1RdGTZ-g
"""

raw_log = "ID:001#NAMA:kopi susu gula aren#QTY:3#PRICE:18000;ID:002#NAMA:COFFEE LATTE#QTY:1#PRICE:25000"

list_transaksi = raw_log.split(";")
transaksi_1 = list_transaksi[0]
transaksi_2 = list_transaksi[1]
atribut_t1 = transaksi_1.split("#")
atribut_t2 = transaksi_2.split("#")

nama_1 = atribut_t1[1].replace("NAMA:", "").strip().title()
qty_1 = int(atribut_t1[2].replace("QTY:", "").strip())
harga_1 = int(atribut_t1[3].replace("PRICE:", "").strip())

nama_2 = atribut_t2[1].replace("NAMA:", "").strip().title()
qty_2 = int(atribut_t2[2].replace("QTY:", "").strip())
harga_2 = int(atribut_t2[3].replace("PRICE:", "").strip())

subtotal_1 = qty_1 * harga_1
subtotal_2 = qty_2 * harga_2
total_pendapatan = subtotal_1 + subtotal_2

print("="*55)
print(f"{'LAPORAN HARIAN KEDAI SOU SPACE':^55}")
print("="*55)
print(f"{'MENU':<25} {'QTY':<5} {'HARGA':<10} {'SUBTOTAL'}")
print("-"*55)
print(f"{nama_1:<25} {qty_1:<5} {harga_1:<10} {subtotal_1}")
print(f"{nama_2:<25} {qty_2:<5} {harga_2:<10} {subtotal_2}")
print("-"*55)
print(f"{'TOTAL PENDAPATAN HARI INI:':<25} Rp {total_pendapatan}")
print("="*55)

"""Double Splitting untuk Organisasi Data: Langkah awal adalah membedah raw_log yang merupakan satu baris teks panjang
. Kita menggunakan fungsi .split(";") untuk memecah string tersebut menjadi kumpulan transaksi dalam sebuah list
. Selanjutnya, setiap elemen transaksi dipecah kembali dengan .split("#") agar kita bisa mengisolasi atribut spesifik seperti ID, Nama, dan Harga melalui teknik indexing
.
Advanced Cleaning (Eliminasi Label): Data mentah tersebut masih membawa label teks seperti "NAMA:" atau "PRICE:" yang tidak relevan untuk laporan
. Di sini, kita mengimplementasikan fungsi .replace() untuk menimpa label tersebut dengan string kosong, yang secara teknis berfungsi menghapus karakter tersebut
. Tak lupa, fungsi .strip() digunakan untuk menjamin presisi data dengan menghapus spasi yang tidak diinginkan di awal atau akhir teks
.
Standardisasi Format dengan Title Case: Agar tampilan laporan terlihat profesional dan seragam, kita melakukan transformasi pada nama menu menggunakan fungsi .title()
. Fungsi ini secara otomatis mengubah format teks menjadi Title Case, di mana huruf pertama setiap kata menjadi kapital
.
Eksplisit Casting ke Numerik: Karena Python secara default membaca data hasil splitting sebagai string, kita tidak bisa langsung melakukan perhitungan matematika
. Oleh karena itu, dilakukan konversi tipe data secara eksplisit (casting) menggunakan fungsi konstruktor int()
. Langkah ini wajib agar data QTY dan PRICE berubah menjadi integer yang valid untuk diolah secara aritmatika
.
Perhitungan Aritmatika Keuangan: Setelah data dikonversi menjadi numerik, kita melakukan kalkulasi untuk mendapatkan subtotal tiap transaksi dan akumulasi total pendapatan harian
. Tanpa proses casting sebelumnya, operasi perkalian pada string hanya akan mengulang teks tersebut dan bukan menghasilkan nilai nominal
.
Formatting Laporan via F-String: Tahap final adalah penyajian data menggunakan F-String (String Interpolation) yang merupakan fitur modern Python untuk menyisipkan variabel ke dalam template string secara efisien
. Kita menambahkan pengaturan alignment (perataan kolom) agar output laporan yang dihasilkan benar-benar rapi, presisi, dan sesuai dengan format tabel yang diminta
.
"""